name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 2.0.2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  csv: ^6.0.0
  easy_localization: ^3.0.7
  http: ^1.2.2
  path_provider: ^2.1.3
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2